# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41bd455acd9379d494dae2d1d4dcd815b4d8cb78e1bd6559fbe9255bd24b5cda738d3b82310f1fc9c397cad8ffcf37ccfedec41b18295485f9ae16fd057a763f

test:
  secret_key_base: 0e4e4f8dd311f812d3d298e88aa7a73424e9397882852aa46fe8989bf59d24c205b1fd24836e84097f3e9492b0ac6fa28b86acac2e6055e392ab95efb3b5f895

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
